[pytest]
testpaths = tests
filterwarnings =
    ignore:The 'app' shortcut is now deprecated:DeprecationWarning:httpx
    ignore:.*utcnow.*:DeprecationWarning:jose
    ignore:.*utcnow.*:DeprecationWarning:passlib
