"""Add reminder_sent to tasks

Revision ID: ed68e4ef9a54
Revises: 455668f2ba1b
Create Date: 2026-04-04 23:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed68e4ef9a54'
down_revision: Union[str, Sequence[str], None] = '455668f2ba1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_sent', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_sent')
    # ### end Alembic commands ###
